# Generated by Django 5.1 on 2025-12-28 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название станции ТО')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('slot_duration', models.PositiveIntegerField(default=60, verbose_name='Длительность слота (мин)')),
            ],
            options={
                'verbose_name': 'Станция ТО',
                'verbose_name_plural': 'Станции ТО',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='booking.carbrand')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
                'ordering': ['name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, verbose_name='Госномер')),
                ('vin', models.CharField(blank=True, max_length=32, null=True, verbose_name='VIN')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.carbrand', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.carmodel', verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(verbose_name='Конец')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('vin', models.CharField(blank=True, max_length=32, null=True, verbose_name='VIN')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.car', verbose_name='Автомобиль')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Запись на ТО',
                'verbose_name_plural': 'Записи на ТО',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='StationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('work_start', models.TimeField(verbose_name='Начало работы')),
                ('work_end', models.TimeField(verbose_name='Конец работы')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'График работы станции',
                'verbose_name_plural': 'Графики работы станций',
                'ordering': ['date'],
                'unique_together': {('station', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StationWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('work_start', models.TimeField(verbose_name='Начало работы')),
                ('work_end', models.TimeField(verbose_name='Конец работы')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='booking.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Недельный график станции',
                'verbose_name_plural': 'Недельные графики станций',
                'ordering': ['weekday'],
                'unique_together': {('station', 'weekday')},
            },
        ),
    ]
