# Generated by Django 5.1 on 2026-01-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_brand_alter_carmodel_options_alter_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
