# Generated by Django 5.1 on 2026-01-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('PASSENGER', 'Легковой'), ('TRUCK', 'Грузовой')], default='PASSENGER', max_length=20, verbose_name='Тип автомобиля'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Легковая'), ('TRUCK', 'Грузовая')], default='CAR', max_length=10),
        ),
    ]
