# Generated by Django 5.1 on 2026-01-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_car_vehicle_type_carmodel_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Легковая'), ('TRUCK', 'Грузовая')], default='CAR', max_length=10, verbose_name='Тип ТС'),
        ),
    ]
