# Generated by Django 5.1 on 2026-01-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_car_options_alter_car_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Легковой'), ('TRUCK', 'Грузовой')], default='CAR', max_length=10, verbose_name='Тип ТС'),
        ),
    ]
