# Generated by Django 5.1 on 2026-01-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_car_is_active_alter_carmodel_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Запланировано'), ('CANCELLED', 'Отменено'), ('DONE', 'Выполнено'), ('NO_SHOW', 'Не приехал')], default='BOOKED', max_length=20),
        ),
    ]
