# Generated by Django 5.1 on 2026-03-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_indexes_and_fixes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentphoto',
            options={'verbose_name': 'Фото записи', 'verbose_name_plural': 'Фото записей'},
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='booking_app_station_aab72c_idx',
            old_name='booking_apt_station_start_end_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='booking_app_user_id_c42d45_idx',
            old_name='booking_apt_user_start_idx',
        ),
        migrations.AddField(
            model_name='station',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='station',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Запланировано'), ('CANCELLED', 'Отменено'), ('DONE', 'Выполнено'), ('NO_SHOW', 'Не приехал')], default='BOOKED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
