# Generated by Django 5.1 on 2026-03-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_appointmentphoto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна для записи'),
        ),
    ]
