# Generated by Django 5.2.17 on 2026-08-31 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0020_remove_userprofile_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointmentlog",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Запись в журнале",
                "verbose_name_plural": "Журнал записей",
            },
        ),
        migrations.AlterField(
            model_name="appointmentlog",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="booking.appointment",
                verbose_name="Запись",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentlog",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто изменил",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentlog",
            name="comment",
            field=models.TextField(blank=True, default="", verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="appointmentlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Время"),
        ),
        migrations.AlterField(
            model_name="appointmentlog",
            name="new_status",
            field=models.CharField(max_length=20, verbose_name="Новый статус"),
        ),
        migrations.AlterField(
            model_name="appointmentlog",
            name="old_status",
            field=models.CharField(blank=True, max_length=20, verbose_name="Старый статус"),
        ),
    ]
