# Generated by Django 5.2.17 on 2026-09-08 18:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deduplication_key', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(default='generic', max_length=32)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('sender', models.TextField(blank=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('expected_start', models.DateTimeField(blank=True, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Отправляется'), ('sent', 'Принято почтовым сервером'), ('failed', 'Попытки исчерпаны'), ('cancelled', 'Устарело')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('lock_token', models.UUIDField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.appointment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Исходящее письмо',
                'verbose_name_plural': 'Очередь писем',
                'indexes': [models.Index(fields=['status', 'available_at'], name='outbox_pending_idx'), models.Index(fields=['status', 'locked_until'], name='outbox_lease_idx')],
            },
        ),
    ]
