# Generated by Django 5.2.17 on 2026-09-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_email_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notification_revision',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='expected_revision',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
