# Generated by Django 5.2.17 on 2026-09-14 21:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_car_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название марки'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='VIN-код'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='booking.brand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.appointment', verbose_name='Запись на ТО'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='auth_token',
            field=models.CharField(blank=True, max_length=128, verbose_name='Токен доступа'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='available_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующая попытка'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='body',
            field=models.TextField(verbose_name='Текст письма'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='deduplication_key',
            field=models.CharField(max_length=64, unique=True, verbose_name='Ключ защиты от повторной отправки'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='expected_revision',
            field=models.PositiveIntegerField(default=0, verbose_name='Версия записи'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='expected_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемое время записи'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='kind',
            field=models.CharField(choices=[('generic', 'Общее уведомление'), ('password', 'Установка или восстановление пароля'), ('welcome', 'Доступ сотрудника станции'), ('booking', 'Подтверждение записи клиенту'), ('reschedule', 'Перенос записи'), ('cancellation', 'Отмена записи клиенту'), ('reminder', 'Напоминание о записи'), ('staff_booking', 'Новая запись для станции'), ('staff_cancellation', 'Отмена записи для станции')], default='generic', max_length=32, verbose_name='Тип письма'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='last_error',
            field=models.CharField(blank=True, max_length=128, verbose_name='Последняя ошибка'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='lock_token',
            field=models.UUIDField(blank=True, null=True, verbose_name='Токен блокировки'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Блокировка до'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='recipient',
            field=models.EmailField(max_length=254, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='sender',
            field=models.TextField(blank=True, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Отправляется'), ('sent', 'Принято почтовым сервером'), ('failed', 'Попытки исчерпаны'), ('cancelled', 'Устарело')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='subject',
            field=models.TextField(verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
